### ISSUE TITLE
Does not work with hashie 2.1.0+

### ISSUE THREAD

**Issue by p-originate** [YotpoLtd/geoip2#2]
Running rake when hashie 2.1.1 is installed there are many failures which all look like this:

<pre>
     Failure/Error: @response = Geoip2.country('62.219.147.28')
     TypeError:
       superclass mismatch for class Rash
     # ./lib/geoip2/client.rb:79:in `block in connection'
     # ./lib/geoip2/client.rb:74:in `connection'
     # ./lib/geoip2/client.rb:39:in `block in get'
     # ./lib/geoip2/client.rb:67:in `call'
     # ./lib/geoip2/client.rb:67:in `block in preform'
     # ./lib/geoip2/client.rb:66:in `preform'
     # ./lib/geoip2/client.rb:38:in `get'
     # ./lib/geoip2/api/country.rb:5:in `country'
     # ./lib/geoip2.rb:65:in `method_missing'
     # ./spec/api/country_spec.rb:7:in `block (4 levels) in <top (required)>'
     # ./spec/api/country_spec.rb:6:in `block (3 levels) in <top (required)>'
</pre>

Hashie 2.1.1 defines Rash which is different from rash's Rash.

**Comment by vladshub** [comment]
@p-originate, @abrambailey Sorry for the long response (didn't notice that there are updates here)
We don't use Rash in our gem... The Rash gem seems to be deprecated and have moved into the [Hashie project](https://github.com/intridea/hashie#rash). So if you will update hashie to a greater version you will not have this issue.
